format_version: v1.0
configName: same51_curiosity
folderName: OLEDC
frameworkPath: C:\MCHP\MCC
processor: ATSAME51J20A
projectName: OLEDC
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME51_DFP\3.6.130\atdf\ATSAME51J20A.atdf
